@startuml
control cycler as "Cycler"
participant action as "action: LongConsumer"
participant input as "input: LongProvider"

== set action ==

[-> cycler: set action
create action
cycler -> action : set

== set cycle provider ==

[-> cycler: set input
create input
cycler -> input : set

== iteration ==

    loop while active
    cycler -> input: getNext()
    activate input
    cycler <<-- input: cyclenum: long
    deactivate input

    cycler -> action: accept(cyclenum)
    activate action
    cycler <<-- action:
    deactivate action

end

@enduml