@startuml
scale 350 width
[*] --> Initialized: new()
Initialized --> Started : thread start()
Started --> StopRequestedByExternal : controller request
Started --> StopRequestedByInternal : thread request
StopRequestedByInternal --> Stopped
StopRequestedByExternal --> Stopped
Stopped --> Initialized : reset
Stopped --> Started : start()
@enduml